name: Build & Test

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - { version: "3.9", env: "py39" }
          - { version: "3.10", env: "py310" }
          - { version: "3.11", env: "py311" }
        include:
          - # Earliest supported version:
            os: ubuntu-20.04
            python: { version: "3.9.8", env: "py39" }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: Setup requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-ci.txt

      - name: Build & Test
        run: |
          pipx run --spec tox==4.4.6 \
            tox run -e ${{ matrix.python.env }}

      - name: Build
        run: |
          pipx run --spec poetry==1.4.0 \
            poetry build --format=sdist

      - name: Build docs
        run: |
          pipx run --spec poetry==1.4.0 \
            poetry install --all-extras
          pipx run --spec poetry==1.4.0 \
            poetry run sh ./scripts/build-doc

      - name: Upload wheel
        if: ${{ matrix.build-format }} == 'wheel'
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: dist/**.whl

  build-doc:
    name: Build Doc
    needs: [build]
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-doc.yml

  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
