name: ci

on:
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: macOS-latest
    steps:
    - name: Install Talon
      run: brew install --cask talon
    - name: Open Talon
      run: open /Applications/Talon.app
    - run: ls ~/.talon